allowBuilds:
  '@parcel/watcher': true
  '@sentry-internal/node-cpu-profiler': true
  core-js: true
  esbuild: true
  msw: true
  sharp: true
  unrs-resolver: true
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/engines'
  - '@sentry-internal/node-cpu-profiler'
  - core-js
  - esbuild
  - msw
  - prisma
  - sharp
  - unrs-resolver
