allowBuilds:
  '@parcel/watcher': true
  '@sentry-internal/node-cpu-profiler': true
  core-js: true
  esbuild: true
  msw: true
  sharp: true
  unrs-resolver: true
  '@prisma/engines': true
  prisma: true
